---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 22:50:00 UTC
# Updated: 2025-09-10 — Initial implementation of audit trail logic
#
# Purpose: Write a structured audit line and a Markdown report, both stamped with the correlation ID.

- name: Ensure audit log directory exists
  file:
    path: "{{ env_guard.paths.env_guard_logs_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Shorten correlation ID for filenames
  set_fact:
    cid8: "{{ (env_guard_correlation_id | regex_replace('[^0-9a-zA-Z]', ''))[0:8] }}"
  delegate_to: localhost

- name: Compute run id (UTC)
  set_fact:
    run_id: "{{ lookup('pipe','date -u +%Y%m%dT%H%M%SZ') }}"
  delegate_to: localhost

- name: Define run folder
  set_fact:
    run_dir: "{{ env_guard.paths.env_guard_logs_dir }}/{{ run_id }}"
  delegate_to: localhost

- name: Define report name
  set_fact:
    report_name: "{{ env_guard.audit.report_prefix }}_{{ run_id }}_{{ cid8 }}.md"
  delegate_to: localhost

- name: Ensure run folder exists
  file:
    path: "{{ run_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Write audit log entry (per-run only)
  lineinfile:
    path: "{{ run_dir }}/{{ env_guard.audit.log_file }}"
    line: "{{ ansible_date_time.iso8601 }} {{ env_guard_correlation_id }} {{ env_guard_user }} {{ validated_env | upper }} APPROVED risk={{ env_guard_risk_score }} hosts={{ target_host_count }} justification=\"{{ deployment_justification }}\""
    create: yes
    mode: '0644'
  delegate_to: localhost

- name: Generate validation report (per-run only)
  copy:
    content: |
      # Environment Guard Validation Report
      **Environment:** {{ validated_env }}
      **Risk:** {{ env_guard_risk_score }}/10
      **Status:** APPROVED
      **User:** {{ env_guard_user }}
      **Date:** {{ env_guard_timestamp }}
      **Correlation ID:** {{ env_guard_correlation_id }}
      **Justification:** {{ deployment_justification }}
    dest: "{{ run_dir }}/{{ report_name }}"
    mode: '0644'
  delegate_to: localhost

- name: Update latest symlink (POSIX)
  file:
    src: "{{ run_dir }}"
    path: "{{ env_guard.paths.env_guard_logs_dir }}/latest"
    state: link
    force: true
  when: (ansible_system | default('Linux')) != 'Windows'
  delegate_to: localhost

- name: Update latest marker file (Windows)
  copy:
    content: "{{ run_dir }}\n"
    dest: "{{ env_guard.paths.env_guard_logs_dir }}/LATEST_RUN_PATH.txt"
    mode: '0644'
  delegate_to: localhost
