---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 22:10:00 UTC
# Updated: 2025-09-10 — Initial implementation of dynamic ansible_host resolution
#
# Purpose: Resolve ansible_host dynamically from environment mappings and track successful mappings.

- name: Map IP addresses for validated environment
  set_fact:
    ansible_host: >-
      {{
        (
          group_names
          | map('extract', environments[validated_env])
          | select('defined')
          | list
          | map('selectattr', 'name', 'equalto', inventory_hostname)
          | map('list')
          | sum(start=[])
          | map(attribute='ip')
          | list
          | first
        )
        if environments[validated_env] is defined else omit
      }}
  when:
  - group_names | length > 0
  - environments is defined
  - validated_env is defined

- name: Track mapped hosts
  set_fact:
    mapped_hosts: "{{ mapped_hosts | default([]) + [inventory_hostname] }}"
  when: ansible_host is defined
