name: connectivity-test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run connectivity_test isolated harness
      run: |
        ansible-playbook -i roles/common/connectivity_test/tests/inventory/test_inventory.ini \
          roles/common/connectivity_test/tests/test_role.yml -v
      env:
        EGF_CORR_ID: "ci-${{ github.run_id }}"

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: connectivity-artifacts
        path: roles/common/connectivity_test/tests/test_logs/*
