# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "proxmox" {
  endpoint  = "https://192.168.0.27:8006/api2/json"
  api_token = "automation@pam!infra-token=83533b51-1a4a-40b6-b498-16c4f3ab69ad"
  insecure  = true

  ssh {
    agent    = true
    username = "root"
  }
}
