---
policy:
  rto_minutes: 15
  rpo_minutes: 5
  autoscale:
    add_workers: 2
    scale_out_cpu_threshold: 70
    scale_in_cpu_threshold: 40
  decision:
    prefer_cloud_with_credits: true
    cloud_priority: [ "azure", "gcp", "onprem" ]
    max_cost_per_hour_usd: 5
