---
# =============================================================================
# Risk Assessment and Scoring Engine (Fixed)
# =============================================================================

- name: "Get current time information"
  set_fact:
    _current_datetime:
      weekday: "{{ ansible_date_time.weekday }}" # 0=Monday, 6=Sunday
      weekday_name: "{{ ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'][ansible_date_time.weekday | int] }}"
      time: "{{ ansible_date_time.time }}"
      hour: "{{ ansible_date_time.hour | int }}"

- name: "Calculate deployment window status"
  set_fact:
    _window_config: "{{ env_guard.deployment.windows[_resolved_environment.deployment_window] }}"

- name: "Check deployment window permission"
  set_fact:
    _window_permitted: >-
      {{
        (_current_datetime.weekday_name in _window_config.days) and
        (_current_datetime.time >= _window_config.hours.start) and
        (_current_datetime.time <= _window_config.hours.end)
      }}

- name: "Calculate deployment risk factors"
  set_fact:
    _risk_factors_computed:
      environment: "{{ _resolved_environment.risk_level }}"
      scope: "{{ (ansible_play_hosts | length | log(2) + 1) | round(0, 'floor') | int }}"
      timing: "{{ 5 if not (_window_permitted | bool) else 1 }}"
      user: "{{ 1 if _user_authorized else 3 }}"

- name: "Compute overall risk score"
  set_fact:
    _computed_risk_score: >-
      {{
        (
          (_risk_factors_computed.environment | int * _risk_factors.environment_weight) +
          (_risk_factors_computed.scope | int * _risk_factors.scope_weight) +
          (_risk_factors_computed.timing | int * _risk_factors.timing_weight) +
          (_risk_factors_computed.user | int * _risk_factors.user_weight)
        ) | round(1)
      }}

- name: "Determine risk category"
  set_fact:
    _risk_category: >-
      {%- if _computed_risk_score | float <= 3 -%}LOW {%- elif _computed_risk_score | float <= 6 -%}MEDIUM {%- elif _computed_risk_score | float <= 8 -%}HIGH {%- else -%}CRITICAL{%- endif -%}

- name: "Risk assessment summary"
  debug:
    msg: |
      📊 RISK ASSESSMENT COMPLETE
      ├── Overall Score: {{ _computed_risk_score }}/10 ({{ _risk_category }})
      ├── Environment Risk: {{ _risk_factors_computed.environment }}/10
      ├── Scope Risk: {{ _risk_factors_computed.scope }}/10 ({{ ansible_play_hosts | length }} hosts)
      ├── Timing Risk: {{ _risk_factors_computed.timing }}/10
      ├── User Risk: {{ _risk_factors_computed.user }}/10
      └── Window Status: {{ 'PERMITTED' if _window_permitted else 'RESTRICTED' }}
