---
# =============================================================================
# Security and Authorization Validation
# =============================================================================

- name: "Check user authorization"
  set_fact:
    _user_authorized: "{{ _security_context.user in env_guard.security.rbac.policies.homelab_admin }}"

- name: "Validate access for high-risk environments"
  fail:
    msg: |
      ❌ HOMELAB ACCESS DENIED

      User: {{ _security_context.user }}
      Environment: {{ _canonical_env }}
      Required: homelab_admin privileges

      Authorized users: {{ env_guard.security.rbac.policies.homelab_admin | join(', ') }}

      Contact homelab administrator for access.
  when:
  - not _user_authorized
  - _resolved_environment.risk_level >= 5

- name: "Security validation complete"
  debug:
    msg: "✅ User '{{ _security_context.user }}' authorized for {{ _canonical_env }} environment"
