#!/usr/bin/env bash
set -euo pipefail

# Fetch Jenkins secrets from Azure Key Vault before Jenkins starts.
# Reads AZURE_* and AZURE_KEYVAULT_URL from /etc/jenkins.akv.env (one-time file)
# or from the environment. Writes /etc/jenkins.env with JENKINS_ADMIN_PASSWORD.

ENV_ONE_TIME="/etc/jenkins.akv.env"
OUT_ENV="/etc/jenkins.env"

# Load env (one-time file preferred)
if [[ -f "$ENV_ONE_TIME" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_ONE_TIME"
fi

required=(AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID AZURE_CLIENT_ID AZURE_CLIENT_SECRET AZURE_KEYVAULT_URL)
for k in "${required[@]}"; do
  if [[ -z "${!k:-}" ]]; then
    echo "prestart-fetch-akv: missing $k; skipping AKV fetch (Jenkins will start without injected secrets)"
    exit 0
  fi
done

# Derive vault name from URL
KV_NAME="$(echo "$AZURE_KEYVAULT_URL" | sed -e 's#https://##' -e 's#\.vault\.azure\.net/*##' )"

echo "prestart-fetch-akv: logging into Azure (service principal)"
az login --service-principal   -u "$AZURE_CLIENT_ID"   -p "$AZURE_CLIENT_SECRET"   --tenant "$AZURE_TENANT_ID" >/dev/null

set +e
ADMIN_PASS=$(az keyvault secret show --vault-name "$KV_NAME" --name "jenkins-admin-password" --query value -o tsv 2>/dev/null)
if [[ -z "$ADMIN_PASS" ]]; then
  ADMIN_PASS=$(az keyvault secret show --vault-name "$KV_NAME" --name "JENKINS_ADMIN_PASSWORD" --query value -o tsv 2>/dev/null)
fi
set -e

if [[ -z "$ADMIN_PASS" ]]; then
  echo "prestart-fetch-akv: no admin password secret found in AKV; aborting inject"
  az account clear >/dev/null || true
  exit 0
fi

tmp=$(mktemp)
{
  echo "# Generated by prestart-fetch-akv on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "JENKINS_ADMIN_PASSWORD=${ADMIN_PASS}"
} > "$tmp"
chmod 600 "$tmp"
chown root:root "$tmp"
mv "$tmp" "$OUT_ENV"

echo "prestart-fetch-akv: wrote $OUT_ENV (env for JCasC)"
az account clear >/dev/null || true

# One-time cleanup of sensitive bootstrap env file
if [[ -f "$ENV_ONE_TIME" ]]; then
  if grep -qE '^(ONE_TIME|PERSIST)=1' "$ENV_ONE_TIME"; then
    shred -u "$ENV_ONE_TIME" || rm -f "$ENV_ONE_TIME"
    echo "prestart-fetch-akv: removed $ENV_ONE_TIME (one-time)"
  fi
fi

exit 0
