# Replace and place this file at the ROOT of the role repo you publish.
namespace: your_namespace
name: role_name
version: 0.1.0
readme: README.md
description: >
  Short description of what this role configures.
license: MIT-0
authors:
- Your Name <you@example.com>
tags:
- hybrid
- kubernetes
- rke2
- linux
repository: "https://github.com/your-handle/ansible-role-role_name"
issues: "https://github.com/your-handle/ansible-role-role_name/issues"
build_ignore:
- .github
- molecule
- tests
- .gitignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- SUPPORT.md
min_ansible_version: "2.12"
platforms:
- name: EL
  versions: [ "8", "9" ]
- name: Ubuntu
  versions: [ "20.04", "22.04" ]
dependencies: {}
