interfaces:
  - name: Port-channel1
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q

  - name: Ethernet0/0
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q

  - name: Ethernet0/1
    status: no shutdown
    port: no switchport
    ip_address: 10.10.40.81
    subnet_mask: 255.255.255.252
    duplex: auto

  - name: Ethernet0/2
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 10

  - name: Ethernet0/3
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 20

  - name: Ethernet1/0
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet1/1
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet1/2
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet1/3
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet2/0
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q
    channel_group: 1
    channel_group_mode: active

  - name: Ethernet2/1
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q
    channel_group: 1
    channel_group_mode: active

  - name: Ethernet2/2
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q
    channel_group: 1
    channel_group_mode: active

  - name: Ethernet2/3
    status: no shutdown
    switchport_mode: trunk
    encapsulation: dot1q
    channel_group: 1
    channel_group_mode: active
  - name: Ethernet3/0
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet3/1
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30

  - name: Ethernet3/2
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30
    shutdown: true

  - name: Ethernet3/3
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 30
    shutdown: true

  - name: Ethernet4/0
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 40

  - name: Ethernet4/1
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 40

  - name: Ethernet4/2
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 40

  - name: Ethernet4/3
    status: no shutdown
    switchport_mode: access
    switchport_access_vlan: 40

vlans:
  - id: 1
    name: default
    ip_address: 172.16.13.17
    subnet_mask: 255.255.255.0
    status: no shutdown

router_ospf:
  id: 1
  router_id: 2.2.2.2
  networks:
    - address: 10.10.40.32
      wildcard_mask: 0.0.0.15
      area: 0.0.0.0
    - address: 10.10.40.48
      wildcard_mask: 0.0.0.7
      area: 0.0.0.0
    - address: 10.10.40.76
      wildcard_mask: 0.0.0.3
      area: 0.0.0.0
    - address: 10.10.40.80
      wildcard_mask: 0.0.0.3
      area: 0.0.0.0
