---

# decision/config.yaml (example)
min_credit: 50
currency: GBP
last_used_cloud: null
sources:
  env_overrides: true
  prometheus_textfile: decision/credits.prom
  azure_cli:
    enabled: false
  gcp_bigquery:
    enabled: false
