---
# SPDX-License-Identifier: MIT-0
# tasks file for int_config

- block:
  - name: "task_one - {{ task_one }}"
    template:
      src: "{{ base_config_template }}"
      dest: /tmp/base_config.txt

  - name: "task_two - {{ task_two }}"
    cisco.ios.ios_config:
      src: /tmp/base_config.txt
    register: base_config_result

  - name: "task_three - {{ task_three }}"
    debug:
      var: base_config_result

  - name: "task_four - {{ task_four }}"
    cisco.ios.ios_config:
      commands:
      - "show running-config | section interface"
    register: interface_running_config

  rescue:
  - name: Handle failure in base config tasks
    debug:
      msg: "An error occurred during base config tasks. Please check previous output."

  always:
  - name: "task_five - {{ task_five }}"
    debug:
      msg: "{{ interface_running_config }}"
