---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 22:20:00 UTC
# Updated: 2025-09-10 — Initial implementation of prerequisite validation and CID seeding
#
# Purpose: Validate prerequisites for IP mapping and seed correlation ID (CID) for traceable logging.

- name: Ensure correlation ID for logging
  when: ipmapper_use_cid
  block:
  - name: Seed CID from defaults
    set_fact:
      cid: "{{ ipmapper_cid_pre | default('', true) }}"

  - name: Generate CID if missing
    when: (cid | default('')) | length == 0
    block:
    - set_fact:
        _cid32: "{{ lookup('password','/dev/null length=32 chars=hexdigits') | lower }}"
    - set_fact:
        cid: "{{ _cid32[0:8] ~ '-' ~ _cid32[8:12] ~ '-' ~ _cid32[12:16] ~ '-' ~ _cid32[16:20] ~ '-' ~ _cid32[20:32] }}"

  - name: Start banner
    debug:
      msg: "[cid={{ cid }}] ipmapper flow started"

- name: Validate env_guard integration
  assert:
    that:
    - validated_env is defined
    - correlation_id is defined
    fail_msg: "Missing env_guard integration. Ensure env_guard role runs before ip_mapper."

- name: Validate environment data
  assert:
    that:
    - environments is defined
    - environments[validated_env] is defined
    fail_msg: "Environment '{{ validated_env }}' not defined in environments data."

- name: Set working target list
  set_fact:
    working_targets: "{{ target_hosts | default(selected_hosts) | default(groups['all']) | default([]) }}"
