---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 22:40:00 UTC
# Updated: 2025-09-10 — Initial implementation of inventory rendering logic
#
# Purpose: Render environment-specific inventory (hosts.ini) and optionally copy it to test_output_dir.

- name: Set inventory paths
  ansible.builtin.set_fact:
    inventory_path: "{{ [inventory_base_path, env] | path_join }}"
    inventory_file: "{{ [inventory_base_path, env, 'hosts.ini'] | path_join }}"
  delegate_to: localhost
  run_once: true

- name: Ensure environment inventory directory exists
  ansible.builtin.file:
    path: "{{ inventory_path }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Render hosts.ini from template
  ansible.builtin.template:
    src: "hosts.j2" # Rename to hosts.ini.j2 if preferred
    dest: "{{ inventory_file }}"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Verify hosts.ini exists
  ansible.builtin.stat:
    path: "{{ inventory_file }}"
  register: inventory_file_check
  delegate_to: localhost
  run_once: true

- name: Fail if inventory was not generated
  ansible.builtin.fail:
    msg: "Missing inventory file: {{ inventory_file }}"
  when: not inventory_file_check.stat.exists
  delegate_to: localhost
  run_once: true

# Evaluate test_output_dir flag safely
- name: Evaluate test_output_dir flag
  block:
  - name: Compute _use_test_output_dir
    ansible.builtin.set_fact:
      _use_test_output_dir: "{{ (test_output_dir | default('') | string | trim) != '' }}"
    delegate_to: localhost
    run_once: true
  rescue:
  - name: Disable test_output_dir on eval error
    ansible.builtin.set_fact:
      _use_test_output_dir: false
    delegate_to: localhost
    run_once: true

- name: Copy hosts.ini to test_output_dir
  when: _use_test_output_dir | default(false)
  block:
  - name: Ensure test_output_dir exists
    ansible.builtin.file:
      path: "{{ test_output_dir | realpath }}"
      state: directory
      mode: '0755'
    delegate_to: localhost
    run_once: true

  - name: Copy hosts.ini to test_output_dir
    ansible.builtin.copy:
      src: "{{ inventory_file }}"
      dest: "{{ (test_output_dir | realpath) + '/hosts.' + env + '.ini' }}"
      remote_src: true
      mode: '0644'
    delegate_to: localhost
    run_once: true

- name: Summary
  ansible.builtin.debug:
    msg: "Generated inventory file: {{ inventory_file }} for env={{ env }}"
  delegate_to: localhost
  run_once: true
