# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/user/hybridops-studio/infra/terraform/live-v1/.terragrunt-state/staging/00-foundation/proxmox/sdn.tfstate"
  }
}
