---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridhub.live)
# Updated: 2025-09-01 17:30:16 UTC
#
# Purpose: Captures user selection method and validates input.

- name: Display menu and get selection method
  pause:
    prompt: "{{ menu_text }}"
  register: method_input

- name: Set method
  set_fact:
    method: "{{ method_input.user_input | upper }}"

- name: Validate method input
  fail:
    msg: "{{ messages.invalid_method }}"
  when: method not in ['A', 'B', 'C', 'D']

- name: Use environment from env_guard
  set_fact:
    env: "{{ validated_env }}"
