---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridhub.live)
# Created: 2025-08-30 12:19:10 UTC
# Updated: 2025-09-01 17:30:16 UTC
#
# Purpose: Orchestrates host selection workflow. Requires env_guard validation.

- name: Validate environment from env_guard
  fail:
    msg: "Environment required from env_guard framework. Use env_guard role first."
  when: validated_env is not defined

- name: Handle user input and method selection
  include_tasks: input_handling.yml

- name: Execute Method A - Manual entry
  include_tasks: method_a_manual.yml
  when: method == "A"

- name: Execute Method B - Group selection
  include_tasks: method_b_groups.yml
  when: method == "B"

- name: Execute Method C - Hierarchical browsing
  include_tasks: method_c_hierarchical.yml
  when: method == "C"

- name: Execute Method D - All hosts
  include_tasks: method_d_all_hosts.yml
  when: method == "D"

- name: Create dynamic groups
  include_tasks: dynamic_group_creation.yml
