---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridhub.live)
# Updated: 2025-08-30 15:33:28 UTC
#
# Purpose: Select all hosts by flattening every category group into target_hosts.

- name: Flatten all category groups
  set_fact:
    all_groups_flat: "{{ categories.values() | map(attribute='groups') | flatten | list }}"

- name: Set all hosts from all groups
  set_fact:
    target_hosts: "{{ all_groups_flat | map('extract', groups) | flatten | select('defined') | list }}"
