---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridhub.live)
# Updated: 2025-08-30 15:33:28 UTC
#
# Purpose: Navigate categories → groups and set target_hosts.

- name: Cache category keys (order as provided)
  set_fact:
    category_keys: "{{ categories.keys() | list }}"

- name: Build category menu
  set_fact:
    category_menu: |-
      Select category:
      {% for i in range(category_keys | length) -%}
      [{{ i + 1 }}] {{ categories[category_keys[i]].name }}
      {%- endfor %}
      Enter category number:

- name: Prompt for category
  pause:
    prompt: "{{ category_menu }}"
  register: category_input

- name: Validate and set selected category
  set_fact:
    selected_category_index: "{{ (category_input.user_input | int) - 1 }}"
    selected_category_key: "{{ category_keys[(category_input.user_input | int) - 1] | default('') }}"
  failed_when: >
    (category_input.user_input | int) <= 0 or (category_input.user_input | int) > (category_keys | length)

- name: Build group menu for category
  set_fact:
    group_menu: |-
      {{ categories[selected_category_key].name }} — Select group:
      {% for i in range(categories[selected_category_key].groups | length) -%}
      [{{ i }}] {{ categories[selected_category_key].groups[i] }}
      {%- endfor %}
      Enter group number:

- name: Prompt for group
  pause:
    prompt: "{{ group_menu }}"
  register: group_input

- name: Validate and set selected group
  set_fact:
    group_index: "{{ group_input.user_input | int }}"
    selected_group: "{{ categories[selected_category_key].groups[group_input.user_input | int] | default('') }}"
  failed_when: >
    (group_input.user_input | int) < 0 or (group_input.user_input | int) >= (categories[selected_category_key].groups | length)

- name: Set hosts from hierarchical selection
  set_fact:
    target_hosts: "{{ groups[selected_group] | default([]) }}"
