---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 21:25:00 UTC
# Updated: 2025-09-10 — Initial orchestration logic for host_selector
#
# Purpose: Orchestrates host selection; depends on env_guard for environment validation.

- name: Ensure correlation ID for logging
  when: host_selector_use_cid
  block:
  - name: Seed CID from defaults
    set_fact:
      cid: "{{ host_selector_cid_pre | default('', true) }}"

  - name: Generate CID if missing
    when: (cid | default('')) | length == 0
    block:
    - set_fact:
        _cid32: "{{ lookup('password','/dev/null length=32 chars=hexdigits') | lower }}"
    - set_fact:
        cid: "{{ _cid32[0:8] ~ '-' ~ _cid32[8:12] ~ '-' ~ _cid32[12:16] ~ '-' ~ _cid32[16:20] ~ '-' ~ _cid32[20:32] }}"

  - name: Start banner
    debug:
      msg: "[cid={{ cid }}] host_selector flow started"

- name: Validate environment from env_guard
  fail:
    msg: "Environment required from env_guard framework. Use env_guard role first."
  when: validated_env is not defined

- name: Handle user input and method selection
  include_tasks: input_handling.yml

- name: Execute Method A - Manual entry
  include_tasks: method_a_manual.yml
  when: method == "A"

- name: Execute Method B - Group selection
  include_tasks: method_b_groups.yml
  when: method == "B"

- name: Execute Method C - Hierarchical browsing
  include_tasks: method_c_hierarchical.yml
  when: method == "C"

- name: Execute Method D - All hosts
  include_tasks: method_d_all_hosts.yml
  when: method == "D"

- name: Create dynamic groups
  include_tasks: dynamic_group_creation.yml
