---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-10 21:55:00 UTC
# Updated: 2025-09-10 — Initial implementation of Method D (all-hosts selection)
#
# Purpose: Select all hosts by flattening category groups into target_hosts.

- name: Method D | Start
  when: host_selector_use_cid | default(false)
  debug:
    msg: "[cid={{ cid | default('') }}] Method D: all hosts"
    verbosity: 1

- name: Flatten all category groups
  set_fact:
    all_groups_flat: "{{ categories.values() | map(attribute='groups') | flatten | list }}"

- name: Compute existing inventory groups
  set_fact:
    existing_group_names: "{{ all_groups_flat | select('in', (groups.keys() | list)) | unique | list }}"

- name: Compute missing inventory groups
  set_fact:
    missing_group_names: "{{ (all_groups_flat | unique | list) | difference(groups.keys() | list) | list }}"

- name: Warn on missing inventory groups (verbose)
  when: missing_group_names | length > 0
  debug:
    msg: "{{ ('[cid=' ~ (cid | default('')) ~ '] ') if (host_selector_use_cid | default(false)) else '' }}Ignoring missing inventory groups: {{ missing_group_names | join(', ') }}"
    verbosity: 1

- name: Fail if no existing inventory groups found
  fail:
    msg: "No matching inventory groups for Method D. Check categories vs inventory."
  when: existing_group_names | length == 0

- name: Set all hosts from existing groups
  set_fact:
    target_hosts: "{{ existing_group_names | map('extract', groups) | flatten | select('defined') | unique | list }}"

- name: Report total host count (verbose)
  debug:
    msg: "{{ ('[cid=' ~ (cid | default('')) ~ '] ') if (host_selector_use_cid | default(false)) else '' }}All-hosts selection → Groups: {{ existing_group_names | length }} (missing {{ missing_group_names | length }}) → Hosts: {{ target_hosts | length }}"
    verbosity: 1
