---
# SPDX-License-Identifier: MIT-0
# Author: Jeleel Muibi (hybridops.studio)
# Created: 2025-09-09 21:39:57 UTC
# Updated: 2025-09-10 — Initial implementation of connectivity result compiler
#
# Purpose: Normalize per-host test results into structured test_results facts.

- name: Compute booleans
  set_fact:
    __icmp_ok: "{{ (ping_result is defined and ping_result.rc is defined and ping_result.rc == 0) }}"
    __ssh_ok: "{{ (ssh_result is defined and (ssh_result.elapsed | default(0)) >= 0 and (ssh_result.failed | default(false)) == false) }}"
    __telnet_ok: "{{ (telnet_result is defined and (telnet_result.elapsed | default(0)) >= 0 and (telnet_result.failed | default(false)) == false) }}"
    __http_ok: "{{ (http_result is defined and (http_result.elapsed | default(0)) >= 0 and (http_result.failed | default(false)) == false) }}"
    __http_head_ok: "{{ (http_head_result is defined and (http_head_result.status | default(0)) in [200,301,302,401,403]) }}"
    __https_ok: "{{ (https_result is defined and (https_result.elapsed | default(0)) >= 0 and (https_result.failed | default(false)) == false) }}"
    __https_head_ok: "{{ (https_head_result is defined and (https_head_result.status | default(0)) in [200,301,302,401,403]) }}"

- name: Resolve CID
  set_fact:
    __cid: "{{ connectivity_cid_pre | default('') }}"

- name: Build test_results
  set_fact:
    test_results:
      cid: "{{ __cid | default('') }}"
      env: "{{ env | default('na') }}"
      hostname: "{{ inventory_hostname }}"
      ip: "{{ ansible_host | default(inventory_hostname) }}"
      icmp: "{{ __icmp_ok | bool }}"
      ssh: "{{ __ssh_ok | bool }}"
      telnet: "{{ __telnet_ok | bool }}"
      http: "{{ __http_ok | bool }}"
      http_head: "{{ __http_head_ok | bool }}"
      https: "{{ __https_ok | bool }}"
      https_head: "{{ __https_head_ok | bool }}"
      ts_utc: "{{ ansible_date_time.iso8601 }}"
      tested_by: "{{ ansible_user_id | default('unknown') }}"

- name: Summary
  debug:
    msg: "[cid={{ __cid | default('') }}] {{ inventory_hostname }} ({{ ansible_host | default(inventory_hostname) }}) ICMP={{ (__icmp_ok | bool) | ternary('OK','X') }} SSH={{ (__ssh_ok | bool) | ternary('OK','X') }} TELNET={{ (__telnet_ok | bool) | ternary('OK','X') }} HTTP={{ (__http_ok | bool) | ternary('OK','X') }} HTTPS={{ (__https_ok | bool) | ternary('OK','X') }}"
