name: gitops-dry-run
on:
  pull_request:
    paths:
    - 'deployment/gitops/**'
  push:
    branches: [ main ]
    paths:
    - 'deployment/gitops/**'

jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install kustomize
      run: |
        curl -sSfL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
        sudo mv kustomize /usr/local/bin/kustomize

    - name: Build overlays
      run: |
        mkdir -p out
        for env in dev stage dr; do
          kustomize build deployment/gitops/overlays/$env > out/gitops_$env.yaml || exit 1
        done

    - name: Upload manifests
      uses: actions/upload-artifact@v4
      with:
        name: gitops-manifests
        path: out/*.yaml
