name: pre-commit
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Install Terraform & TFLint (for terraform hooks)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y unzip
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o tf.zip
        sudo unzip -o tf.zip -d /usr/local/bin && rm tf.zip
        curl -fsSL https://github.com/terraform-linters/tflint/releases/download/v0.50.3/tflint_linux_amd64.zip -o tflint.zip
        sudo unzip -o tflint.zip -d /usr/local/bin && rm tflint.zip

    - name: Run pre-commit
      run: pre-commit run --all-files
